### ISSUE TITLE
Materias - Banco de Dados na FATEC de Bauru

### ISSUE THREAD

**Issue by omarkdev** [Webschool-io/Ensino-Superior-de-Informatica-GRATUITO#2]
As matérias que tenho no curso de Banco de Dados na FATEC de Bauru.
## Banco de Dados

Resolvi colocar todas as matérias, acho que fica mais organizado.
- Comunicação e Expressão
- Arquitetura e Organização de Computadores
- Matemática Discreta
- Inglês
- Fundamentos da Administração
- Algoritmos
- Planejamento Estratégico 
- Arquitetura e Modelagem de Dados
- Linguagem de Programação I e II
- Fundamento de Gestão de Pessoas
- Fundamentos de Cálculo
- Engenharia de Software
- Programação de Banco de Dados
- Estatística Descritiva
- Estrutura de Dados
- Fundamento de Redes e Computadores
- Gestão de TI
- Sistemas operacionais centralizados e distribuídos
- Metodologia de pesquisa científica
- Programação Avançada de Banco de Dados
- Administração de Banco de Dados
- Padrões e projetos de sistemas
- Fundamentos de Gestão de Projetos
- Projeto Datawarehouse
- Banco de Dados distribuídos
- Projeto de Graduação I e II
- Tecnologia Ambiente
- Laboratório de Projeto de Banco de Dados
- Legislação Aplicada TI
- Projeto de Banco de Dados não estruturados
- Otimização de Banco de Dados
- Gestão de processo de desenvolvimento de software
- Tópicos avançados de Banco de Dados

**Comment by suissa** [comment]
Mande igual o Leo https://github.com/Webschool-io/Ensino-Superior-de-Informatica-GRATUITO/tree/master/cursos
